##
 # This file is part of the Curator package.
 # Copyright © 2011 Quentin Hill <quentin@quentinhill.com>
 # 
 # For the full copyright and license information, please view the LICENSE
 # file that was distributed with this source code.
 ##


# Files to skip - fnmatch() compatible strings expected
skip: ['*.swp', '*.bak', '.DS_Store', 'Empty']
